version: "3.8"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile-prod
    environment:
      NODE_ENV: production
    ports:
      - "8080:80"
    restart: always
