version: "3.8"
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    restart: always
