import {
  OSMEducationAmenities,
  OSMEntertainmentAmenities,
  OSMFacilitiesAmenities,
  OSMFinancialAmenities,
  OSMHealthcareAmenities,
  OSMOthersAmenities,
  OSMPublicServicesAmenities,
  OSMSustenanceAmenities,
  OSMTransportationAmenities,
  OSMWasteManagementAmenities,
  PermittedAmenities,
} from '../../../features/find-address/api/types';

const permittedAmenities: PermittedAmenities = {
  [OSMOthersAmenities.AnimalBoarding]: true,
  [OSMOthersAmenities.AnimalBreeding]: true,
  [OSMOthersAmenities.AnimalShelter]: true,
  [OSMOthersAmenities.AnimalTraining]: true,
  [OSMEntertainmentAmenities.ArtsCentre]: true,
  [OSMFinancialAmenities.Atm]: true,
  [OSMHealthcareAmenities.BabyHatch]: true,
  [OSMOthersAmenities.BakingOven]: true,
  [OSMFinancialAmenities.Bank]: true,
  [OSMSustenanceAmenities.Bar]: true,
  [OSMFacilitiesAmenities.Bbq]: true,
  [OSMFacilitiesAmenities.Bench]: true,
  [OSMTransportationAmenities.BicycleParking]: true,
  [OSMTransportationAmenities.BicycleRental]: true,
  [OSMTransportationAmenities.BicycleRepairStation]: true,
  [OSMSustenanceAmenities.Biergarten]: true,
  [OSMTransportationAmenities.BoatRental]: true,
  [OSMTransportationAmenities.BoatSharing]: true,
  [OSMEntertainmentAmenities.Brothel]: true,
  [OSMFinancialAmenities.BureauDeChange]: true,
  [OSMTransportationAmenities.BusStation]: true,
  [OSMSustenanceAmenities.Cafe]: true,
  [OSMTransportationAmenities.CarRental]: true,
  [OSMTransportationAmenities.CarSharing]: true,
  [OSMTransportationAmenities.CarWash]: true,
  [OSMEntertainmentAmenities.Casino]: true,
  [OSMTransportationAmenities.ChargingStation]: true,
  [OSMEntertainmentAmenities.Cinema]: true,
  [OSMHealthcareAmenities.Clinic]: true,
  [OSMOthersAmenities.Clock]: true,
  [OSMEducationAmenities.College]: true,
  [OSMEntertainmentAmenities.CommunityCentre]: true,
  [OSMTransportationAmenities.CompressedAir]: true,
  [OSMEntertainmentAmenities.ConferenceCentre]: true,
  [OSMPublicServicesAmenities.Courthouse]: true,
  [OSMOthersAmenities.Crematorium]: true,
  [OSMEducationAmenities.DancingSchool]: true,
  [OSMHealthcareAmenities.Dentist]: true,
  [OSMOthersAmenities.DiveCentre]: true,
  [OSMHealthcareAmenities.Doctors]: true,
  [OSMFacilitiesAmenities.DogToilet]: true,
  [OSMFacilitiesAmenities.DressingRoom]: true,
  [OSMFacilitiesAmenities.DrinkingWater]: true,
  [OSMTransportationAmenities.DriverTraining]: true,
  [OSMEducationAmenities.DrivingSchool]: true,
  [OSMEntertainmentAmenities.EventsVenue]: true,
  [OSMEntertainmentAmenities.ExhibitionCentre]: true,
  [OSMSustenanceAmenities.FastFood]: true,
  [OSMTransportationAmenities.FerryTerminal]: true,
  [OSMPublicServicesAmenities.FireStation]: true,
  [OSMEducationAmenities.FirstAidSchool]: true,
  [OSMSustenanceAmenities.FoodCourt]: true,
  [OSMEntertainmentAmenities.Fountain]: true,
  [OSMTransportationAmenities.Fuel]: true,
  [OSMOthersAmenities.FuneralHall]: true,
  [OSMEntertainmentAmenities.Gambling]: true,
  [OSMFacilitiesAmenities.GiveBox]: true,
  [OSMOthersAmenities.GraveYard]: true,
  [OSMTransportationAmenities.GritBin]: true,
  [OSMHealthcareAmenities.Hospital]: true,
  [OSMOthersAmenities.HuntingStand]: true,
  [OSMSustenanceAmenities.IceCream]: true,
  [OSMOthersAmenities.InternetCafe]: true,
  [OSMEducationAmenities.Kindergarten]: true,
  [OSMOthersAmenities.Kitchen]: true,
  [OSMOthersAmenities.KneippWaterCure]: true,
  [OSMEducationAmenities.LanguageSchool]: true,
  [OSMEducationAmenities.Library]: true,
  [OSMOthersAmenities.Lounger]: true,
  [OSMEntertainmentAmenities.LoveHotel]: true,
  [OSMFacilitiesAmenities.Mailroom]: true,
  [OSMOthersAmenities.Marketplace]: true,
  [OSMOthersAmenities.Monastery]: true,
  [OSMTransportationAmenities.MotorcycleParking]: true,
  [OSMEducationAmenities.MusicSchool]: true,
  [OSMEntertainmentAmenities.MusicVenue]: true,
  [OSMEntertainmentAmenities.Nightclub]: true,
  [OSMHealthcareAmenities.NursingHome]: true,
  [OSMFacilitiesAmenities.ParcelLocker]: true,
  [OSMTransportationAmenities.Parking]: true,
  [OSMTransportationAmenities.ParkingEntrance]: true,
  [OSMTransportationAmenities.ParkingSpace]: true,
  [OSMHealthcareAmenities.Pharmacy]: true,
  [OSMOthersAmenities.PhotoBooth]: true,
  [OSMOthersAmenities.PlaceOfMourning]: true,
  [OSMOthersAmenities.PlaceOfWorship]: true,
  [OSMEntertainmentAmenities.Planetarium]: true,
  [OSMPublicServicesAmenities.Police]: true,
  [OSMPublicServicesAmenities.PostBox]: true,
  [OSMPublicServicesAmenities.PostDepot]: true,
  [OSMPublicServicesAmenities.PostOffice]: true,
  [OSMPublicServicesAmenities.Prison]: true,
  [OSMSustenanceAmenities.Pub]: true,
  [OSMOthersAmenities.PublicBath]: true,
  [OSMEntertainmentAmenities.PublicBookcase]: true,
  [OSMPublicServicesAmenities.RangerStation]: true,
  [OSMWasteManagementAmenities.Recycling]: true,
  [OSMOthersAmenities.RefugeeSite]: true,
  [OSMEducationAmenities.ResearchInstitute]: true,
  [OSMSustenanceAmenities.Restaurant]: true,
  [OSMWasteManagementAmenities.SanitaryDumpStation]: true,
  [OSMEducationAmenities.School]: true,
  [OSMFacilitiesAmenities.Shelter]: true,
  [OSMFacilitiesAmenities.Shower]: true,
  [OSMEntertainmentAmenities.SocialCentre]: true,
  [OSMHealthcareAmenities.SocialFacility]: true,
  [OSMEntertainmentAmenities.Stripclub]: true,
  [OSMEntertainmentAmenities.Studio]: true,
  [OSMEducationAmenities.SurfSchool]: true,
  [OSMEntertainmentAmenities.Swingerclub]: true,
  [OSMTransportationAmenities.Taxi]: true,
  [OSMFacilitiesAmenities.Telephone]: true,
  [OSMEntertainmentAmenities.Theatre]: true,
  [OSMFacilitiesAmenities.Toilets]: true,
  [OSMPublicServicesAmenities.Townhall]: true,
  [OSMEducationAmenities.ToyLibrary]: true,
  [OSMEducationAmenities.TrafficPark]: true,
  [OSMEducationAmenities.Training]: true,
  [OSMEducationAmenities.University]: true,
  [OSMTransportationAmenities.VehicleInspection]: true,
  [OSMOthersAmenities.VendingMachine]: true,
  [OSMHealthcareAmenities.Veterinary]: true,
  [OSMWasteManagementAmenities.WasteBasket]: true,
  [OSMWasteManagementAmenities.WasteDisposal]: true,
  [OSMWasteManagementAmenities.WasteTransferStation]: true,
  [OSMFacilitiesAmenities.WaterPoint]: true,
  [OSMFacilitiesAmenities.WateringPlace]: true,
};

export { permittedAmenities };
